# Generated by Django 4.2.6 on 2023-11-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateMaterial',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_update_by', models.CharField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateMaterials',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('gate_material_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gatematerial')),
                ('gate_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gate')),
            ],
        ),
        migrations.DeleteModel(
            name='BuildingGate',
        ),
        migrations.DeleteModel(
            name='FenceGate',
        ),
        migrations.RemoveField(
            model_name='gatefunction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gatetype',
            name='name',
        ),
        migrations.AddField(
            model_name='gatefunction',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatefunction',
            name='last_update_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatefunction',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatetype',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatetype',
            name='last_update_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatetype',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
