# Generated by Django 4.2.6 on 2023-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gatematerial_gatematerials_delete_buildinggate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatefunction',
            name='primary_function',
            field=models.CharField(blank=True, choices=[('E', 'Electric'), ('A', 'Automatic'), ('M', 'Manual')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gatematerial',
            name='material',
            field=models.CharField(blank=True, choices=[('B', 'Barbed Wire'), ('C', 'Chain-Link'), ('F', 'Field Fence'), ('R', 'Wood Rail'), ('I', 'Wrought Iron')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gatetype',
            name='primary_type',
            field=models.CharField(blank=True, choices=[('V', 'Vehicle Access'), ('F', 'Footpath Access'), ('L', 'Lamb Creep'), ('S', 'Step-Over')], max_length=1, null=True),
        ),
    ]
