# Generated by Django 4.2.6 on 2023-11-07 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gatefunction_primary_function_gatematerial_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='gate_direction_from_hinge_when_closed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_open_maximum_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_open_minimum_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='height_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='is_date_estimated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='last_update_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='uuid',
            field=models.UUIDField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gate',
            name='width_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatefunction',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gatematerial',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gatematerial',
            name='uuid',
            field=models.UUIDField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatematerials',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gatematerials',
            name='last_update_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatematerials',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatematerials',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatematerials',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gatetype',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gatetype',
            name='uuid',
            field=models.UUIDField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
