# Generated by Django 4.2.6 on 2023-11-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_gate_gate_direction_from_hinge_when_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(default=1234),
            preserve_default=False,
        ),
    ]
