# Generated by Django 4.2.6 on 2023-11-07 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_update_by', models.CharField(blank=True, null=True)),
                ('name', models.CharField()),
                ('notes', models.CharField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('width_m', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateTimeField(blank=True, null=True)),
                ('is_date_estimated', models.BooleanField(blank=True, null=True)),
                ('gate_direction_from_hinge_when_closed', models.FloatField(blank=True, null=True)),
                ('gate_open_maximum_degrees', models.FloatField(blank=True, null=True)),
                ('gate_open_minimum_degrees', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateFunction',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_update_by', models.CharField(blank=True, null=True)),
                ('primary_function', models.CharField(blank=True, choices=[('E', 'Electric'), ('A', 'Automatic'), ('M', 'Manual')], max_length=1, null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateMaterial',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_update_by', models.CharField(blank=True, null=True)),
                ('material', models.CharField(blank=True, choices=[('B', 'Barbed Wire'), ('C', 'Chain-Link'), ('F', 'Field Fence'), ('R', 'Wood Rail'), ('I', 'Wrought Iron')], max_length=1, null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_update_by', models.CharField(blank=True, null=True)),
                ('primary_type', models.CharField(blank=True, choices=[('V', 'Vehicle Access'), ('F', 'Footpath Access'), ('L', 'Lamb Creep'), ('S', 'Step-Over')], max_length=1, null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateMaterials',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_update_by', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('gate_material_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gatematerial')),
                ('gate_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gate')),
            ],
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_function_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gatefunction'),
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_type_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gatetype'),
        ),
    ]
